import { 
  AppType, 
  RecommendChannel, 
  AlgorithmType,
  ServiceStatus,
} from '../constants'
import type { WaterfallSlotConfig } from '../types'

// Mock数据 - 瀑布流坑位配置
export const mockWaterfallData: WaterfallSlotConfig[] = [
  // 闪峰 - 大首页
  {
    id: 1,
    app: AppType.SHANFENG,
    channel: RecommendChannel.DELIVERY,
    slotPosition: 1,
    algorithmId: 1,
    algorithmName: '無敵星星-首頁版',
    algorithmType: AlgorithmType.INVINCIBLE_STAR,
    purchaseLimit: { days: 7, quantity: 3 },
    merchantLimit: 'unlimited',
    regionLimit: 'limited',
    regionIds: [1, 2],
    status: ServiceStatus.ENABLED,
    updatedBy: 'admin',
    updatedAt: '2024-01-20 14:20:00',
    createdAt: '2024-01-15 10:30:00',
  },
  {
    id: 2,
    app: AppType.SHANFENG,
    channel: RecommendChannel.DELIVERY,
    slotPosition: 3,
    algorithmId: 6,
    algorithmName: '猜你喜歡-主力版',
    algorithmType: AlgorithmType.GUESS_YOU_LIKE,
    purchaseInterval: 2,
    merchantLimit: 'limited',
    merchantIds: [101, 102],
    regionLimit: 'unlimited',
    status: ServiceStatus.ENABLED,
    updatedBy: 'admin',
    updatedAt: '2024-01-21 10:30:00',
    createdAt: '2024-01-16 09:15:00',
  },
  {
    id: 3,
    app: AppType.SHANFENG,
    channel: RecommendChannel.DELIVERY,
    slotPosition: 5,
    algorithmId: 2,
    algorithmName: '新店廣告-外賣版',
    algorithmType: AlgorithmType.NEW_STORE_AD,
    purchaseLimit: { days: 14, quantity: 5 },
    merchantLimit: 'unlimited',
    regionLimit: 'unlimited',
    status: ServiceStatus.DISABLED,
    updatedBy: 'operator',
    updatedAt: '2024-01-22 16:45:00',
    createdAt: '2024-01-17 11:20:00',
  },
  // 闪峰 - 外卖频道
  {
    id: 4,
    app: AppType.SHANFENG,
    channel: RecommendChannel.DELIVERY,
    slotPosition: 1,
    algorithmId: 2,
    algorithmName: '新店廣告-外賣版',
    algorithmType: AlgorithmType.NEW_STORE_AD,
    purchaseLimit: { days: 7, quantity: 3 },
    merchantLimit: 'unlimited',
    regionLimit: 'unlimited',
    status: ServiceStatus.ENABLED,
    updatedBy: 'admin',
    updatedAt: '2024-01-20 14:20:00',
    createdAt: '2024-01-15 10:30:00',
  },
  {
    id: 5,
    app: AppType.SHANFENG,
    channel: RecommendChannel.DELIVERY,
    slotPosition: 2,
    algorithmId: 6,
    algorithmName: '猜你喜歡-主力版',
    algorithmType: AlgorithmType.GUESS_YOU_LIKE,
    purchaseInterval: 3,
    merchantLimit: 'unlimited',
    regionLimit: 'limited',
    regionIds: [1],
    status: ServiceStatus.ENABLED,
    updatedBy: 'admin',
    updatedAt: '2024-01-21 10:30:00',
    createdAt: '2024-01-16 09:15:00',
  },
  // mFood - 大首页
  {
    id: 6,
    app: AppType.MFOOD,
    channel: RecommendChannel.DELIVERY,
    slotPosition: 1,
    algorithmId: 1,
    algorithmName: '無敵星星-首頁版',
    algorithmType: AlgorithmType.INVINCIBLE_STAR,
    purchaseLimit: { days: 7, quantity: 3 },
    merchantLimit: 'unlimited',
    regionLimit: 'limited',
    regionIds: [1, 2],
    status: ServiceStatus.ENABLED,
    updatedBy: 'admin',
    updatedAt: '2024-01-20 14:20:00',
    createdAt: '2024-01-15 10:30:00',
  },
  {
    id: 7,
    app: AppType.MFOOD,
    channel: RecommendChannel.DELIVERY,
    slotPosition: 2,
    algorithmId: 5,
    algorithmName: '流量廣告-全渠道',
    algorithmType: AlgorithmType.TRAFFIC_AD,
    purchaseLimit: { days: 30, quantity: 10 },
    merchantLimit: 'limited',
    merchantIds: [103],
    regionLimit: 'unlimited',
    status: ServiceStatus.ENABLED,
    updatedBy: 'operator',
    updatedAt: '2024-01-22 16:45:00',
    createdAt: '2024-01-17 11:20:00',
  },
  {
    id: 8,
    app: AppType.MFOOD,
    channel: RecommendChannel.DELIVERY,
    slotPosition: 4,
    algorithmId: 6,
    algorithmName: '猜你喜歡-主力版',
    algorithmType: AlgorithmType.GUESS_YOU_LIKE,
    purchaseInterval: 2,
    merchantLimit: 'unlimited',
    regionLimit: 'unlimited',
    status: ServiceStatus.DISABLED,
    updatedBy: 'admin',
    updatedAt: '2024-01-23 09:00:00',
    createdAt: '2024-01-18 14:30:00',
  },
  // mFood - 团购频道
  {
    id: 9,
    app: AppType.MFOOD,
    channel: RecommendChannel.GROUP_BUY,
    slotPosition: 1,
    algorithmId: 3,
    algorithmName: '盤活復蘇-團購版',
    algorithmType: AlgorithmType.HOT_REVIVE_AD,
    purchaseLimit: { days: 14, quantity: 5 },
    merchantLimit: 'unlimited',
    regionLimit: 'unlimited',
    status: ServiceStatus.ENABLED,
    updatedBy: 'admin',
    updatedAt: '2024-01-20 14:20:00',
    createdAt: '2024-01-15 10:30:00',
  },
  {
    id: 10,
    app: AppType.MFOOD,
    channel: RecommendChannel.GROUP_BUY,
    slotPosition: 3,
    algorithmId: 6,
    algorithmName: '猜你喜歡-主力版',
    algorithmType: AlgorithmType.GUESS_YOU_LIKE,
    purchaseInterval: 2,
    merchantLimit: 'limited',
    merchantIds: [101, 102, 103],
    regionLimit: 'limited',
    regionIds: [1, 2, 3],
    status: ServiceStatus.ENABLED,
    updatedBy: 'operator',
    updatedAt: '2024-01-21 10:30:00',
    createdAt: '2024-01-16 09:15:00',
  },
]
