import { createElement } from 'react'
import type { ComponentType, ReactNode } from 'react'
import { Space } from 'antd'
import {
  // 侧边栏菜单图标（按菜单 key 使用）
  HomeOutlined,
  ShopOutlined,
  CrownOutlined,
  PieChartOutlined,
  AppstoreOutlined,
  ColumnHeightOutlined,
  WalletOutlined,
  GiftOutlined,
  RedEnvelopeOutlined,
  FileTextOutlined,
  ShoppingFilled,
  ReadOutlined,
  ThunderboltOutlined,
  BarChartOutlined,
  DashboardOutlined,
  LineChartOutlined,
  SearchOutlined,
  SettingOutlined,
  GlobalOutlined,
  AimOutlined,
  FontSizeOutlined,
  FireOutlined,
  ScissorOutlined,
  SwapOutlined,
  StopOutlined,
  SafetyCertificateOutlined,
  MoneyCollectOutlined,
  AccountBookOutlined,
  FileSearchOutlined,
  AuditOutlined,
  CheckCircleOutlined,
  TeamOutlined,
  UserOutlined,
  ApartmentOutlined,
  IdcardOutlined,
  ScheduleOutlined,
  LockOutlined,
  SolutionOutlined,
  DatabaseOutlined,
  MenuOutlined,
  // 常用操作类图标（供菜单图标选择器选用）
  PlusOutlined,
  DeleteOutlined,
  EditOutlined,
  ExportOutlined,
  ImportOutlined,
  UploadOutlined,
  EyeOutlined,
  EyeInvisibleOutlined,
  SaveOutlined,
  ArrowLeftOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
  ReloadOutlined,
  StarOutlined,
  HeartOutlined,
  BellOutlined,
  CalendarOutlined,
  ClockCircleOutlined,
  TagOutlined,
  FolderOutlined,
  TableOutlined,
  FormOutlined,
  AlertOutlined,
  InfoCircleOutlined,
  QuestionCircleOutlined,
  FilterOutlined,
  AppstoreAddOutlined,
  CloudOutlined,
  LinkOutlined,
  ToolOutlined,
  ExperimentOutlined,
  RocketOutlined,
  FlagOutlined,
  TrophyOutlined,
  BulbOutlined,
  EnvironmentOutlined,
  MailOutlined,
  MessageOutlined,
  MergeCellsOutlined,
  ExpandAltOutlined,
  ShrinkOutlined,
  BranchesOutlined,
} from '@ant-design/icons'

/** 菜单可用图标注册表：图标名称 → 组件（数据库 icon 字段存储名称字符串） */
const ICON_COMPONENTS: Record<string, ComponentType> = {
  'HomeOutlined': HomeOutlined,
  'ShopOutlined': ShopOutlined,
  'CrownOutlined': CrownOutlined,
  'PieChartOutlined': PieChartOutlined,
  'AppstoreOutlined': AppstoreOutlined,
  'ColumnHeightOutlined': ColumnHeightOutlined,
  'WalletOutlined': WalletOutlined,
  'GiftOutlined': GiftOutlined,
  'RedEnvelopeOutlined': RedEnvelopeOutlined,
  'FileTextOutlined': FileTextOutlined,
  'ShoppingFilled': ShoppingFilled,
  'ReadOutlined': ReadOutlined,
  'ThunderboltOutlined': ThunderboltOutlined,
  'BarChartOutlined': BarChartOutlined,
  'DashboardOutlined': DashboardOutlined,
  'LineChartOutlined': LineChartOutlined,
  'SearchOutlined': SearchOutlined,
  'SettingOutlined': SettingOutlined,
  'GlobalOutlined': GlobalOutlined,
  'AimOutlined': AimOutlined,
  'FontSizeOutlined': FontSizeOutlined,
  'FireOutlined': FireOutlined,
  'ScissorOutlined': ScissorOutlined,
  'SwapOutlined': SwapOutlined,
  'StopOutlined': StopOutlined,
  'SafetyCertificateOutlined': SafetyCertificateOutlined,
  'MoneyCollectOutlined': MoneyCollectOutlined,
  'AccountBookOutlined': AccountBookOutlined,
  'FileSearchOutlined': FileSearchOutlined,
  'AuditOutlined': AuditOutlined,
  'CheckCircleOutlined': CheckCircleOutlined,
  'TeamOutlined': TeamOutlined,
  'UserOutlined': UserOutlined,
  'ApartmentOutlined': ApartmentOutlined,
  'IdcardOutlined': IdcardOutlined,
  'ScheduleOutlined': ScheduleOutlined,
  'LockOutlined': LockOutlined,
  'SolutionOutlined': SolutionOutlined,
  'DatabaseOutlined': DatabaseOutlined,
  'MenuOutlined': MenuOutlined,
  'PlusOutlined': PlusOutlined,
  'DeleteOutlined': DeleteOutlined,
  'EditOutlined': EditOutlined,
  'ExportOutlined': ExportOutlined,
  'ImportOutlined': ImportOutlined,
  'UploadOutlined': UploadOutlined,
  'EyeOutlined': EyeOutlined,
  'EyeInvisibleOutlined': EyeInvisibleOutlined,
  'SaveOutlined': SaveOutlined,
  'ArrowLeftOutlined': ArrowLeftOutlined,
  'ArrowUpOutlined': ArrowUpOutlined,
  'ArrowDownOutlined': ArrowDownOutlined,
  'ReloadOutlined': ReloadOutlined,
  'StarOutlined': StarOutlined,
  'HeartOutlined': HeartOutlined,
  'BellOutlined': BellOutlined,
  'CalendarOutlined': CalendarOutlined,
  'ClockCircleOutlined': ClockCircleOutlined,
  'TagOutlined': TagOutlined,
  'FolderOutlined': FolderOutlined,
  'TableOutlined': TableOutlined,
  'FormOutlined': FormOutlined,
  'AlertOutlined': AlertOutlined,
  'InfoCircleOutlined': InfoCircleOutlined,
  'QuestionCircleOutlined': QuestionCircleOutlined,
  'FilterOutlined': FilterOutlined,
  'AppstoreAddOutlined': AppstoreAddOutlined,
  'CloudOutlined': CloudOutlined,
  'LinkOutlined': LinkOutlined,
  'ToolOutlined': ToolOutlined,
  'ExperimentOutlined': ExperimentOutlined,
  'RocketOutlined': RocketOutlined,
  'FlagOutlined': FlagOutlined,
  'TrophyOutlined': TrophyOutlined,
  'BulbOutlined': BulbOutlined,
  'EnvironmentOutlined': EnvironmentOutlined,
  'MailOutlined': MailOutlined,
  'MessageOutlined': MessageOutlined,
  'MergeCellsOutlined': MergeCellsOutlined,
  'ExpandAltOutlined': ExpandAltOutlined,
  'ShrinkOutlined': ShrinkOutlined,
  'BranchesOutlined': BranchesOutlined,
}

/** 全部可用图标名称（用于图标选择器） */
export const MENU_ICON_NAMES = Object.keys(ICON_COMPONENTS)

/** 按图标名称渲染图标组件；未注册或空名称返回 null */
export function renderMenuIcon(name?: string | null): ReactNode {
  if (!name) return null
  const Comp = ICON_COMPONENTS[name]
  return Comp ? createElement(Comp) : null
}

/** 图标选择器下拉选项（带图标预览） */
export function getMenuIconOptions() {
  return MENU_ICON_NAMES.map((name) => ({
    value: name,
    label: (
      <Space size={6}>
        <span style={{ fontSize: 14 }}>{renderMenuIcon(name)}</span>
        <span style={{ fontSize: 13 }}>{name}</span>
      </Space>
    ),
  }))
}
