// Type declarations for auto-generated build-meta module
// Actual implementation is generated by versionFilePlugin during Vite build
declare const BUILD_TIME: string
declare const COMMIT_HASH: string
export { BUILD_TIME, COMMIT_HASH }
